/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Gudang;

import Database.Koneksi;
import java.sql.Connection;
import javax.swing.JOptionPane;
/**
 *
 * @author Nuew
 */
public class FormRequestMasuk_ extends javax.swing.JPanel {
    
    public final Connection conn = new Koneksi().connect();

    public void clear(){
        kodeInput.setText(null);
        namaInput.setText(null);
        jumlahInput.setText(null);
        keteranganInput.setText(null);
        tanggalInput.setDate(null);
    }

    /**
     * Creates new form RequestMasuk_
     */
    public FormRequestMasuk_() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelRequest = new javax.swing.JPanel();
        ContentRequest = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        PanelNama = new javax.swing.JPanel();
        namaLabel = new javax.swing.JLabel();
        namaInput = new javax.swing.JTextField();
        PanelKode = new javax.swing.JPanel();
        kodeLabel = new javax.swing.JLabel();
        kodeInput = new javax.swing.JTextField();
        PanelTanggal = new javax.swing.JPanel();
        tanggalLabel = new javax.swing.JLabel();
        tanggalInput = new com.toedter.calendar.JDateChooser();
        PanelKategori = new javax.swing.JPanel();
        kategoriLabel = new javax.swing.JLabel();
        kategoriInput = new javax.swing.JComboBox<>();
        PanelKeterangan = new javax.swing.JPanel();
        keteranganLabel = new javax.swing.JLabel();
        ScrollKeterangan = new javax.swing.JScrollPane();
        keteranganInput = new javax.swing.JTextArea();
        submitBtn = new javax.swing.JButton();
        PanelJumlah = new javax.swing.JPanel();
        jumlahLabel = new javax.swing.JLabel();
        jumlahInput = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        PanelRequest.setLayout(new java.awt.CardLayout());

        ContentRequest.setBackground(new java.awt.Color(255, 255, 255));

        Title.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Title.setText("Request Masuk Barang");

        PanelNama.setBackground(new java.awt.Color(255, 255, 255));

        namaLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        namaLabel.setForeground(new java.awt.Color(54, 55, 85));
        namaLabel.setText("Nama Barang");

        javax.swing.GroupLayout PanelNamaLayout = new javax.swing.GroupLayout(PanelNama);
        PanelNama.setLayout(PanelNamaLayout);
        PanelNamaLayout.setHorizontalGroup(
            PanelNamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelNamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelNamaLayout.createSequentialGroup()
                        .addComponent(namaLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(namaInput))
                .addContainerGap())
        );
        PanelNamaLayout.setVerticalGroup(
            PanelNamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNamaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(namaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelKode.setBackground(new java.awt.Color(255, 255, 255));

        kodeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kodeLabel.setForeground(new java.awt.Color(54, 55, 85));
        kodeLabel.setText("Kode Barang");

        javax.swing.GroupLayout PanelKodeLayout = new javax.swing.GroupLayout(PanelKode);
        PanelKode.setLayout(PanelKodeLayout);
        PanelKodeLayout.setHorizontalGroup(
            PanelKodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKodeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelKodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelKodeLayout.createSequentialGroup()
                        .addComponent(kodeLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(kodeInput))
                .addContainerGap())
        );
        PanelKodeLayout.setVerticalGroup(
            PanelKodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKodeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kodeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kodeInput, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelTanggal.setBackground(new java.awt.Color(255, 255, 255));

        tanggalLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tanggalLabel.setForeground(new java.awt.Color(54, 55, 85));
        tanggalLabel.setText("Tanggal");

        javax.swing.GroupLayout PanelTanggalLayout = new javax.swing.GroupLayout(PanelTanggal);
        PanelTanggal.setLayout(PanelTanggalLayout);
        PanelTanggalLayout.setHorizontalGroup(
            PanelTanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTanggalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTanggalLayout.createSequentialGroup()
                        .addComponent(tanggalLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tanggalInput, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelTanggalLayout.setVerticalGroup(
            PanelTanggalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTanggalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanggalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tanggalInput, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelKategori.setBackground(new java.awt.Color(255, 255, 255));

        kategoriLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kategoriLabel.setForeground(new java.awt.Color(54, 55, 85));
        kategoriLabel.setText("Kategori");

        kategoriInput.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kategoriInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atribut", "Kendaraan", "Alat", "Pelengkap" }));

        javax.swing.GroupLayout PanelKategoriLayout = new javax.swing.GroupLayout(PanelKategori);
        PanelKategori.setLayout(PanelKategoriLayout);
        PanelKategoriLayout.setHorizontalGroup(
            PanelKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKategoriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelKategoriLayout.createSequentialGroup()
                        .addComponent(kategoriLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(kategoriInput, 0, 569, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelKategoriLayout.setVerticalGroup(
            PanelKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKategoriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kategoriLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kategoriInput, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelKeterangan.setBackground(new java.awt.Color(255, 255, 255));

        keteranganLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        keteranganLabel.setForeground(new java.awt.Color(54, 55, 85));
        keteranganLabel.setText("Keterangan");

        keteranganInput.setColumns(20);
        keteranganInput.setRows(5);
        ScrollKeterangan.setViewportView(keteranganInput);

        javax.swing.GroupLayout PanelKeteranganLayout = new javax.swing.GroupLayout(PanelKeterangan);
        PanelKeterangan.setLayout(PanelKeteranganLayout);
        PanelKeteranganLayout.setHorizontalGroup(
            PanelKeteranganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKeteranganLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelKeteranganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelKeteranganLayout.createSequentialGroup()
                        .addComponent(keteranganLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ScrollKeterangan, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelKeteranganLayout.setVerticalGroup(
            PanelKeteranganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKeteranganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(keteranganLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScrollKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        submitBtn.setBackground(new java.awt.Color(54, 55, 85));
        submitBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        PanelJumlah.setBackground(new java.awt.Color(255, 255, 255));

        jumlahLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jumlahLabel.setForeground(new java.awt.Color(54, 55, 85));
        jumlahLabel.setText("Jumlah");

        javax.swing.GroupLayout PanelJumlahLayout = new javax.swing.GroupLayout(PanelJumlah);
        PanelJumlah.setLayout(PanelJumlahLayout);
        PanelJumlahLayout.setHorizontalGroup(
            PanelJumlahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJumlahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelJumlahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelJumlahLayout.createSequentialGroup()
                        .addComponent(jumlahLabel)
                        .addGap(0, 520, Short.MAX_VALUE))
                    .addComponent(jumlahInput))
                .addContainerGap())
        );
        PanelJumlahLayout.setVerticalGroup(
            PanelJumlahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJumlahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jumlahLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jumlahInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ContentRequestLayout = new javax.swing.GroupLayout(ContentRequest);
        ContentRequest.setLayout(ContentRequestLayout);
        ContentRequestLayout.setHorizontalGroup(
            ContentRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentRequestLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContentRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ContentRequestLayout.createSequentialGroup()
                        .addGroup(ContentRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(PanelKeterangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Title, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelNama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelKode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(ContentRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ContentRequestLayout.setVerticalGroup(
            ContentRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContentRequestLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Title)
                .addGap(34, 34, 34)
                .addGroup(ContentRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContentRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentRequestLayout.createSequentialGroup()
                        .addComponent(PanelKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(ContentRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(ContentRequestLayout.createSequentialGroup()
                        .addComponent(PanelJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        PanelRequest.add(ContentRequest, "card2");

        add(PanelRequest, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        try{
            String kode = kodeInput.getText();
            String nama = namaInput.getText();
            String jumlah = jumlahInput.getText();
            String kategori = kategoriInput.getSelectedItem().toString();
            String status = "waiting";
            String date = String.valueOf(tanggalInput.getDate());
            String keterangan = keteranganInput.getText();
            
            java.sql.Statement stat = conn.createStatement();
            String sql = "INSERT INTO data_masuk (kode_barang,nama_barang,jumlah,kategori,status,keterangan,created_at)  VALUES('"
                    +kode+"','"
                    +nama+"','"
                    +jumlah+"','"
                    +kategori+"','"
                    +status+"','"
                    +keterangan+"','"
                    +date+"');";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data Berhasil diSubmit!");
            clear();
        } catch(Exception error){
            JOptionPane.showMessageDialog(null, "Gagal Submit!");
        }
    }//GEN-LAST:event_submitBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContentRequest;
    private javax.swing.JPanel PanelJumlah;
    private javax.swing.JPanel PanelKategori;
    private javax.swing.JPanel PanelKeterangan;
    private javax.swing.JPanel PanelKode;
    private javax.swing.JPanel PanelNama;
    private javax.swing.JPanel PanelRequest;
    private javax.swing.JPanel PanelTanggal;
    private javax.swing.JScrollPane ScrollKeterangan;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField jumlahInput;
    private javax.swing.JLabel jumlahLabel;
    private javax.swing.JComboBox<String> kategoriInput;
    private javax.swing.JLabel kategoriLabel;
    private javax.swing.JTextArea keteranganInput;
    private javax.swing.JLabel keteranganLabel;
    private javax.swing.JTextField kodeInput;
    private javax.swing.JLabel kodeLabel;
    private javax.swing.JTextField namaInput;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JButton submitBtn;
    private com.toedter.calendar.JDateChooser tanggalInput;
    private javax.swing.JLabel tanggalLabel;
    // End of variables declaration//GEN-END:variables
}
