/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Admin;

/**
 *
 * @author Nuew
 */
public class ShowBarang_ extends javax.swing.JPanel {

    /**
     * Creates new form ShowBarang_
     */
    public ShowBarang_() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelShow = new javax.swing.JPanel();
        ContentShow = new javax.swing.JPanel();
        ScrollShow = new javax.swing.JScrollPane();
        TableShow = new javax.swing.JTable();
        Title = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        PanelShow.setLayout(new java.awt.CardLayout());

        TableShow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "BR001", "Kabel",  new Integer(25), "-", null},
                { new Integer(2), "BR002", "Ban",  new Integer(6), "-", null},
                { new Integer(3), "BR003", "Perkakas",  new Integer(3), "-", null},
                { new Integer(4), "BR004", "Mobil",  new Integer(2), "-", null},
                { new Integer(5), "BR005", "Helmet",  new Integer(15), null, null}
            },
            new String [] {
                "No", "ID", "Nama", "Jumlah", "Kategori", "Aksi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ScrollShow.setViewportView(TableShow);

        Title.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Title.setText("Data Barang");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_example_20px.png"))); // NOI18N
        jButton2.setText("Edit Data");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_add_new_20px.png"))); // NOI18N
        jButton3.setText("Tambah Data");

        javax.swing.GroupLayout ContentShowLayout = new javax.swing.GroupLayout(ContentShow);
        ContentShow.setLayout(ContentShowLayout);
        ContentShowLayout.setHorizontalGroup(
            ContentShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentShowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContentShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollShow, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
                    .addGroup(ContentShowLayout.createSequentialGroup()
                        .addGroup(ContentShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Title)
                            .addGroup(ContentShowLayout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ContentShowLayout.setVerticalGroup(
            ContentShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContentShowLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Title)
                .addGap(18, 18, 18)
                .addGroup(ContentShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ScrollShow, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelShow.add(ContentShow, "card2");

        add(PanelShow, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContentShow;
    private javax.swing.JPanel PanelShow;
    private javax.swing.JScrollPane ScrollShow;
    private javax.swing.JTable TableShow;
    private javax.swing.JLabel Title;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
